sudo: false
before_script:
- npm run dependencies
- bundle install
after_success:
- codeclimate < tests/coverage/report.lcov
- coveralls < tests/coverage/report.lcov
- npm run docs
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_BRANCH" = "master" && npm run deploy || echo "Pull request. Skipping deployment" >&2
cache:
  directories:
  - bower_components
  - node_modules
language: node_js
