language: node_js
sudo: false
cache:
  directories:
  - bower_components
  - node_modules
env:
  global:
    secure: MLWYRa2lxuEmgtRpyr929Y7BDDj4l2YQz9OgfJq3qGuqK1vXsV1A1sQMFlG4GvyNbMhaxedBLIIR9IHHDXTo0aAvhWy8uir55RkGkWZ6+Ywqa9PTimRMbJN296Zt+/Y3ALDcYupp27+UM7o6S+bXK+4lkNvTapRd5Hi/k+QDpIU=
before_script: ./node_modules/.bin/bower install
after_success: codeclimate < tests/coverage/report.lcov
