sudo: false
before_script:
- npm run dependencies
- bundle install
after_success:
- codeclimate < tests/coverage/report.lcov
- coveralls < tests/coverage/report.lcov
- npm run docs
cache:
  directories:
  - bower_components
  - node_modules
language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
